// no "use client" here

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import ClientLayout from "./ClientLayout"; // PC + Mobile 자동 분기


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Loventure",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <head>
        {/* 브라우저/모바일 폼·스크롤 등 라이트모드로 고정 */}
        <meta name="color-scheme" content="light" />
        {/* 모바일 주소창/상태바 톤 고정(라이트모드) */}
        <meta name="theme-color" content="#fdf6e3" />

        {/* 시스템 다크모드 무시하고 강제로 라이트모드 설정 */}
        <meta name="color-scheme" content="light" />
      </head>
      <body>
        {/* 여기서 단 한 번만 ClientLayout으로 감쌉니다 */}
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}

// 원래 코드
// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         <ClientLayout>{children}</ClientLayout>
//       </body>
//     </html>
//   );
// }